### ISSUE TITLE
Augur does not deal with python 2.x any longer it seems

### ISSUE THREAD

**Issue by sgoggins** [OSSHealth/augur#166]
Fresh Amazon AMI.  After getting it to compile, I get this error: 

(augur) [ec2-user@ip-172-31-27-133 logs]$ cat backend.log
Traceback (most recent call last):
  File "/usr/local/bin/augur", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('python-dateutil>=2.5.0'), set(['pandas']))
(augur) [ec2-user@ip-172-31-27-133 logs]$

**Comment by sgoggins** [comment]
I don't actually care if we support Python 2.x ... FYI ... it seems that getting inside the augur virtual environment and issuing this command solves the issue: 
```
conda install python=3.7

```
